### ISSUE TITLE
关于MPCN的复现

### ISSUE THREAD

**Issue by JarenceSJ** [ShomyLiu/Neu-Review-Rec#11]
作者，你好！谢谢你的代码开源分享。我在 amazon 的 Instant Video 和 Toy&Games两个数据集上测试的，遇到了MPCN实验结果不如DeepCoNN的情况。请问一下你们复现MPCN的结果是怎样的？MPCN的实验有什么trick，或者参数需要注意的嘛？

**Comment by ShomyLiu** [comment]
你好，我们测试的MPCN的结果的确在一些数据集效果不太理想。  包括在MPCN原文中给出的baseline结果都很弱，没记错的话， MPCN可能使用数据集是Amazon全部的数据集，而不是常用的small set。

**Comment by JarenceSJ** [comment]
好的，谢谢。
