### ISSUE TITLE
data_pro.py

### ISSUE THREAD

**Issue by PanTings** [ShomyLiu/Neu-Review-Rec#13]
大佬你好，我发现你通过这个代码构造的字典use2id，它的键和值都是i呀，就是说user2id={‘0’:0, '1':1, ...}。这是为什么呢？在你的机器上是正常的吗？
    uidList = userCount.index  # userID list 
    user2id = dict((uid, i) for(i, uid) in enumerate(uidList))

**Comment by PanTings** [comment]
怪不得之前一直报错KeyError，我还以为是文件提取出了问题，没想到是字典user2id的构造出了问题....因为构造字典使用的
uidList = userCount.index 
这个列表的元素就是0,1,2，...。也就是说压根没把reviewID构造进字典里，所以
uid = list(map(lambda x: user2id[x], data['user_id']))
这行代码自然报错KeyError。

**Comment by ShomyLiu** [comment]
你好，我这边重新clone了一份代码，按照readme处理数据，没有问题呀。正常运行。

--------
不过你说的问题按说应该不存在。
```
uidLlist 存储的就是原生ID，不是0,1,2,3....等
```
如下：
![image](https://user-images.githubusercontent.com/10215945/93167389-20a12780-f753-11ea-8630-aab797264747.png)


或许是你的环境或者数据格式不太一致？
我这边环境：
```
python3.6
pandas                        0.25.3
numpy                         1.18.4
```

**Comment by xiwd** [comment]
![Uploading image.png…]()
好像是因为userCount.index的问题，userCount.values才是获取对应的user_id的

**Comment by xiwd** [comment]
```
    # uidList = userCount.index  # userID list
    # iidList = itemCount.index  # itemID list  # 这个地方存在错误，应该value
    uidList = userCount.values
    iidList = itemCount.values
    user2id = dict((uid[0], i) for(i, uid) in enumerate(uidList))
    item2id = dict((iid[0], i) for(i, iid) in enumerate(iidList))
    data = numerize(data)
```
好像是因为userCount.index的问题，userCount.values才是获取user_id的

**Comment by ShomyLiu** [comment]
@xiwd   你好，在 `get_count()`返回的`idListCount` 是一个key为 原id，value为count的Series对象，如下图：
```
> ~/Neu-Review-Rec/pro_data/data_pro.py(30)get_count()
     29     idListCount = idList.size()
---> 30     return idListCount
     31

ipdb> type(idListCount)
<class 'pandas.core.series.Series'>
ipdb> idListCount
user_id
A08161909WK3HU7UYTMW     5
A1020L7BWW9RAX           7
A10323WWTFPSGP           6
A103KNDW8GN92L          30
A103W7ZPKGOCC9          45
                        ..
AZVH70JMJ2IHX           10
AZVHFS4KQBQTK            6
AZWCAUCNLGL4H            6
AZY3MDFJJFI91            8
AZYZA8FDL48GD            7
Length: 5541, dtype: int64
ipdb> idListCount.index
Index(['A08161909WK3HU7UYTMW', 'A1020L7BWW9RAX', 'A10323WWTFPSGP',
       'A103KNDW8GN92L', 'A103W7ZPKGOCC9', 'A105188E1HFWRX', 'A105S56ODHGJEK',
       'A1065Q31DNPRAN', 'A106BECWWKQIC9', 'A107R79K63CE30',
       ...
       'AZSN1TO0JI87B', 'AZT9OGZODW8VW', 'AZTVHB938DIG5', 'AZTZ61W23JET0',
       'AZVA13Q19KURR', 'AZVH70JMJ2IHX', 'AZVHFS4KQBQTK', 'AZWCAUCNLGL4H',
       'AZY3MDFJJFI91', 'AZYZA8FDL48GD'],
      dtype='object', name='user_id', length=5541)
ipdb> idListCount.values
array([5, 7, 6, ..., 6, 8, 7])
```
所以 `userCount.index` 返回是原生id，能说下你那边环境吗？

**Comment by xiwd** [comment]
我这边的环境是
python3.7
pandas 1.1.1
numpy 1.17.3
可能是pandas环境的问题，我这边index返回的不是原生id诶，感觉像是index

**Comment by ShomyLiu** [comment]
@xiwd   你好，我做了测试，的确是pandas版本问题。 我这两天做一个update，尽量避免版本issue，谢谢。

**Comment by FKCHAN** [comment]
你好，我按教程运行pro_data.py 为什么会一点反应也没有呢？
我把.json数据解压，安装环境是
python3.6
pandas                        0.25.3
numpy                         1.18.4
wor2vec.bin放到了pro_data
然后运行命令：python3 data_pro.py Digital_Music_5.json，但是没反应。
就像这样，
(Neu-Review-Rec-master) H:\Neu-Review-Rec-master\pro_data>python3 data_pro.py Digital_Music_5.json

(Neu-Review-Rec-master) H:\Neu-Review-Rec-master\pro_data>
请问是我那一步出错了么？

**Comment by ShomyLiu** [comment]
你好，仅仅根据现在的信息，无法判断问题的原因，建议您手动调试一下，如输出一下等

**Comment by FKCHAN** [comment]
你好，是我环境的问题，
python data_pro.py Digital_Music_5.json
就可以运行了，应该是我用的是anaconda创建的环境，然后用的是conda自带的python环境，所以python3不能识别，希望和我一样情况的小伙伴别被这个卡住。
