### ISSUE TITLE
请问作者这个基于评论文本的深度推荐系统总结还在更新吗？

### ISSUE THREAD

**Issue by zhhhzhang** [ShomyLiu/Neu-Review-Rec#2]
首先感谢大佬的分享！ 受益匪浅！
想问问这个专栏之后还更新吗？
以及这个研究方向的发展如何？

**Comment by ShomyLiu** [comment]
你好！感谢关注。
会保证今年继续更新相关论文介绍。
以及在这个repo内会将一些最新baselines进行 复现。

**Comment by ShomyLiu** [comment]
这个研究方向的发展，个人资历尚浅，不敢随意断言。。简单说的话，从历年顶会文章来看，单纯review-based rec 做 rating prediction的高水平文章 越来越少，各种花式attention都用的差不多了。
但是就review这个信息来说，，很多更复杂的任务值得尝试，比如结合review的generation等。

**Comment by zhhhzhang** [comment]
谢谢啦！ 坐等更新啊&nbsp;



---原始邮件---
发件人: "HT Liu"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 晚上6:25
收件人: "ShomyLiu/Neu-Review-Rec"<Neu-Review-Rec@noreply.github.com&gt;;
抄送: "zhhhzhang"<zhhhzhang@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ShomyLiu/Neu-Review-Rec] 请问作者这个基于评论文本的深度推荐系统总结还在更新吗？ (#2)




 
你好！感谢关注。
 会保证今年继续更新相关论文介绍。
 以及在这个repo内会将一些最新baselines进行 复现。

**Comment by zhhhzhang** [comment]
嗯嗯&nbsp; 我也觉得是generation，单纯attention没啥意思了&nbsp; 但是我总感觉这一块都没人做了 不知道为什么？



---原始邮件---
发件人: "HT Liu"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 晚上6:31
收件人: "ShomyLiu/Neu-Review-Rec"<Neu-Review-Rec@noreply.github.com&gt;;
抄送: "zhhhzhang"<zhhhzhang@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ShomyLiu/Neu-Review-Rec] 请问作者这个基于评论文本的深度推荐系统总结还在更新吗？ (#2)




 
这个研究方向的发展，个人资历尚浅，不敢随意断言。。简单说的话，从历年顶会文章来看，单纯review-based rec 做 rating prediction的高水平文章 越来越少，各种花式attention都用的差不多了。
 但是就review这个信息来说，，很多更复杂的任务值得尝试，比如结合review的generation等。

**Comment by ShomyLiu** [comment]
毕竟也属于小方向， 大头还是再CTR，Session Rec上的

**Comment by zhhhzhang** [comment]
嗯嗯多谢指点！ 期待更新



---原始邮件---
发件人: "HT Liu"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 晚上7:09
收件人: "ShomyLiu/Neu-Review-Rec"<Neu-Review-Rec@noreply.github.com&gt;;
抄送: "zhhhzhang"<zhhhzhang@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ShomyLiu/Neu-Review-Rec] 请问作者这个基于评论文本的深度推荐系统总结还在更新吗？ (#2)




 
毕竟也属于小方向， 大头还是再CTR，Session Rec上的
