### ISSUE TITLE
data_pro.py文件中预定义的宏变量是怎么确定的？

### ISSUE THREAD

**Issue by FrankKirin** [ShomyLiu/Neu-Review-Rec#20]
P_REVIEW = 0.85
MAX_DF = 0.7
MAX_VOCAB = 50000
DOC_LEN = 500
请问一下，这些值是如何得到的？
这些值的变化是否会影响模型性能？

**Comment by ShomyLiu** [comment]
1. 这些参数大部分根据已有工作进行设定的，比如P_REVIEW是根据NARRE来的， MAX_DF,DOC_LEN等根据CARL，ConvMF等
2. 这些数据预处理的超参会影响模型性能。但是还是需要保持一致
