### ISSUE TITLE
所有模型用--output=mlp都会出错，请问是没实现吗？

### ISSUE THREAD

**Issue by MachineGunLin** [ShomyLiu/Neu-Review-Rec#24]
试过了fm、lfm、nfm，还有不指定output参数，都没有问题，只有--output=mlp时会报错，请问是因为没有实现mlp吗？

**Comment by ShomyLiu** [comment]
有实现MLP的，参考： https://github.com/ShomyLiu/Neu-Review-Rec/blob/master/framework/prediction.py#L144
报错的问题是？

**Comment by MachineGunLin** [comment]
![image](https://user-images.githubusercontent.com/18243223/126453429-5cd2b5b1-89e2-43e9-bdcf-312bc0568c27.png)

**Comment by MachineGunLin** [comment]
就是像上图那样报错，其他的prediction方法都是可以的，请问是我使用的姿势不对嘛？

**Comment by ShomyLiu** [comment]
这里的确有个问题，去掉`[0]` 即可：https://github.com/ShomyLiu/Neu-Review-Rec/blob/master/framework/prediction.py#L158
 `return F.relu(self.fc(feature)[0])` ->  `return F.relu(self.fc(feature))`

**Comment by MachineGunLin** [comment]
> 这里的确有个问题，去掉`[0]` 即可：https://github.com/ShomyLiu/Neu-Review-Rec/blob/master/framework/prediction.py#L158
> `return F.relu(self.fc(feature)[0])` -> `return F.relu(self.fc(feature))`

嗯，问题解决了，感谢！
