### ISSUE TITLE
关于复现结果的问题

### ISSUE THREAD

**Issue by lknownothing** [ShomyLiu/Neu-Review-Rec#26]
感谢分享！
我使用readme里默认的Digital_Music数据集，训练了DeepCoNN和NARRE。
1. 发现在DeepCoNN上验证结果为`evaluation reslut: mse: 0.8446; rmse: 0.9190;` 好于NRCA中出现的`mse=1.056`。在NARRE上为`evaluation reslut: mse: 0.8321; rmse: 0.9122; mae: 0.6754` ，差于NRCA文中的`mse=0.812`。
2. 此外，在较大的数据集上Video_Games上，NARRE的mse也只有`1.14`左右，达不到NRCA中的`1.11`。在Toys_and_Games数据集上NARRE和DeepCoNN都是差`0.844`左右。
3. 上述结果，我都是用不同随机数训练3-4次，还是存在和NRCA的差距。

想问下作者在具体复现baselines的时候，还需要注意哪些问题能达到和NRCA中差不多的结果呢。

**Comment by L0ngxhn** [comment]
请问你说的NRCA是论文全称是什么？ # #

**Comment by ShomyLiu** [comment]
@lknownothing  你好！ 最近在忙实验，回复较晚。
是这样的，当时投论文时  比如NARRE的对比算法模型是用论文作者发布的代码来跑的结果。 
而本项目的数据预处理为了统一，跟原文的方法也会有差异，可以对比一下。
