### ISSUE TITLE
关于模型收敛的问题

### ISSUE THREAD

**Issue by MachineGunLin** [ShomyLiu/Neu-Review-Rec#29]
作者你好，小白请教一个问题，请问复现的这几篇论文，分别大概要多少个epoch能收敛呢（默认的超参数下）？ 因为论文里并没提到这一点，另外可能也和实现方式有关？

**Comment by ShomyLiu** [comment]
你好，收敛的话，一般在20个epoch以内都差不多了

**Comment by MachineGunLin** [comment]
谢谢
