### ISSUE TITLE
请问楼主试过换embedding的方法吗？

### ISSUE THREAD

**Issue by MachineGunLin** [ShomyLiu/Neu-Review-Rec#30]
楼主你好，小白又来提问了。我发现这几篇论文很多都在18年之前，如果word embedding换成BERT或者其他方法，是否会对结果有帮助呢？请问楼主试过吗？

**Comment by ShomyLiu** [comment]
因为后续不再做这个放箱令，所以没有试过Bert。 不过应该会有效的，因为评论类型的信息，用word2vec的话， 会有比较多的oov情况出现。
