### ISSUE TITLE
data_pro.py可以处理Digital_Music, 但无法处理其他数据集

### ISSUE THREAD

**Issue by MachineGunLin** [ShomyLiu/Neu-Review-Rec#31]
楼主你好，用data_pro.py处理Digital_Music_5.json文件时可以正常得到数据集，但是处理其他类别的数据集的json文件都是报错：
![image](https://user-images.githubusercontent.com/18243223/130089606-27de6058-d787-41e6-9dcd-6f03ee59f011.png)
请问这里是需要对代码做一些处理吗还是什么？  数据集是从[这里](http://deepyeti.ucsd.edu/jianmo/amazon/index.html)拿的。

**Comment by MachineGunLin** [comment]
我这里下载的是2018的数据集，是因为下载的数据集的格式不同吗？ 楼主的数据集是在哪下载的呢？

**Comment by hongyuntw** [comment]
我也有同樣的問題 求解

**Comment by ShomyLiu** [comment]
这边的数据集是在：https://jmcauley.ucsd.edu/data/amazon/ 这里下载的， 如果格式不同的话，可以调整一下代码，字段名可能会有些区别。

**Comment by hongyuntw** [comment]
> 这边的数据集是在：https://jmcauley.ucsd.edu/data/amazon/ 这里下载的， 如果格式不同的话，可以调整一下代码，字段名可能会有些区别。

謝謝作者，我有找到錯誤 發PR了
感謝您
