### ISSUE TITLE
小白想问一下在训练过程中train data 的mse 和evaluation result 的mse的区别？

### ISSUE THREAD

**Issue by Dream-HanXD** [ShomyLiu/Neu-Review-Rec#32]
loading train data
loading val data
train data: 51764; test data: 6471
start training....
2020-07-28 12:27:58  Epoch 0...
        train data: loss:107503.6215, mse: 2.0768;
        evaluation reslut: mse: 1.2466; rmse: 1.1165; mae: 0.9691;
model save
******************************

train data 的mse 是基于训练集的结果，evaluation result 的呢？

**Comment by ShomyLiu** [comment]
数据集划分是分 训练集，验证集和测试集的。所以evaluation就是关于验证集上的结果
