### ISSUE TITLE
support of top-n recommendation task

### ISSUE THREAD

**Issue by hygeng** [ShomyLiu/Neu-Review-Rec#4]
Firstly, thanks a lot for your contribution to this repository! The great project aggregates the state of the art recommendations of reviews by a unified pipeline, and they are what I am watching at this period. Your work is really awesome and of great help.

Would you have further plans for the support of top-n recommendation tasks? Such as the evaluations based on ranking and metrics like hit rate, NDCG, since I'm trying to taking these as baselines. Thanks!

**Comment by ShomyLiu** [comment]
Hi!  After obtaining the features of uses and item, just change the loss function to fit the ranking tasks.
The objective function of ranking tasks is different from the rating prediction, hence, according to my experience, it is not a good choice to convert into Ranking metrics based on the rating prediction results.

The plan to support top-n rec would be considered after all the models are reimplemented.

**Comment by hygeng** [comment]
> Hi! After obtaining the features of uses and item, just change the loss function to fit the ranking tasks.
> The objective function of ranking tasks is different from the rating prediction, hence, according to my experience, it is not a good choice to convert into Ranking metrics based on the rating prediction results.
> 
> The plan to support top-n rec would be considered after all the models are reimplemented.

Thanks for your reply!

**Comment by hongyuntw** [comment]
@ShomyLiu 您好想請問您
是否可以按照您提供的code train好一個model，再拿此model的結果去做top-k recommendation evaluation (NDCG, HR 等等)!?
這樣是行得通的嗎!?

**Comment by ShomyLiu** [comment]
@hongyuntw  这样理论上没问题的， 本质还是在学习user/item embedding ， 不过最好还是修改一下训练目标，这边model 都是rating prediction，使用MSE loss， Top- 的任务最好还是用ranking loss
