### ISSUE TITLE
验证集和测试集

### ISSUE THREAD

**Issue by Herumw** [ShomyLiu/Neu-Review-Rec#6]
作者你好，想问下你写的train函数的代码是不是没有把验证集和测试集分开，看了下是用测试集的数据来挑选模型，然后再在测试集中检验效果，非常感谢。

**Comment by ShomyLiu** [comment]
你好，我们在数据处理中，将验证集和测试集分开的，两份数据集，如下：
https://github.com/ShomyLiu/Neu-Review-Rec/blob/master/pro_data/data_pro.py#L266
只是后续的训练，并没有严格区分验证和测试， 只用了上述数据集的其中一份，另一份后续测试用。

后续我们会加入模型测试模块，load 训练好的模型进行测试。

**Comment by Herumw** [comment]
哦哦这样，谢谢
