### ISSUE TITLE
DeepCoNN模型中有两次Dropout计算

### ISSUE THREAD

**Issue by JarenceSJ** [ShomyLiu/Neu-Review-Rec#8]
首先谢谢作者的分享，非常感谢！
然后，我发现DeepCoNN存在Dropout重复计算的问题：
两次计算如下
1. model/deepconn.py: line 40-41 
2. framework/models/py: line 41 

取消掉第一次的Dropout计算后，DeepCoNN效果有一定提升。

**Comment by ShomyLiu** [comment]
你好！ 谢谢关注
关于Dropout这里，我们对每个模型都执行了类似的操作：
- 模型部分：user/item feature 进行了一次dropout
- 特征融合之后:  ui feature  又进行了一次dropout

效果肯定会有变化，不同模型可能反馈不同。

**Comment by JarenceSJ** [comment]
感谢！
